# collectible_list.py


# All game NFTs
nft_to_display = [
    "Christmas Tree", "Hoot", "Angel Bear", "Kuebiko", "Foreman Beaver",
    "Russian Flag", "Farm Cat", "Ukrainian Flag", "Iron Idol", "Turkish Flag",
    "Gold Egg", "Chicken Coop", "Mysterious Parsnip", "Nugget", "Indian Flag",
    "Farm Dog", "Apprentice Beaver", "Black Berry", "Cabbage Girl",
    "American Flag", "Rainbow Artist Bear", "Sunflower Rock", "Carrot Sword",
    "Heart of Davy Jones", "Wood Nymph Wendy", "Scarecrow", "Argentinian Flag",
    "Rock Golem", "Squirrel Monkey", "Gnome", "Woody the Beaver",
    "Rocky the Mole", "Peeled Potato", "Blossom Tree", "Ayam Cemani",
    "Rooster", "Cabbage Boy", "Undead Rooster", "French Flag", "Goblin Flag",
    "Rich Bear", "Chinese Flag", "Mysterious Head", "Lady Bug", "Nancy",
    "Tunnel Mole", "Observatory", "Pirate Flag", "Lunar Calendar",
    "Sunflower Flag", "Classy Bear", "Egg Basket", "Nyon Statue",
    "Sunflower Statue", "Blue Egg", "Red Egg", "Victoria Sisters", "Pink Egg",
    "Purple Egg", "Maneki Neko", "Tiki Totem", "Palm Tree", "Sunflower Bear",
    "Giant Carrot", "Valentine Bear", "Pablo The Bunny", "Homeless Tent",
    "Rich Chicken", "Speed Chicken", "Sunflower Tombstone", "Christmas Bear",
    "Fat Chicken", "Flamingo", "Karkinos", "Goblin Crow", "Collectible Bear",
    "Cyborg Bear", "Easter Bunny", "Wicker Man", "Christmas Snow Globe",
    "Farmer Bath", "Easter Bear", "Fountain", "War Tombstone", "Potato Statue",
    "War Skull", "Heart Balloons", "Beach Ball", "Easter Bush",
    "Golden Bonsai", "Badass Bear", "Brilliant Bear", "Chef Bear",
    "Construction Bear", "Farmer Bear", "Whale Bear", "T-Rex Skull",
    "Pirate Bear", "Abandoned Bear", "Algerian Flag", "Australian Flag",
    "Basic Bear", "Basic Scarecrow", "Belgian Flag", "Bonnie's Tombstone",
    "Brazilian Flag", "British Flag", "Obie", "Maximus", "Purple Trail", "Green Amulet", 
    "Beetroot Amulet", "Carrot Amulet", "Sunflower Amulet", "Angel Wings", 
    "Sunflower Shield", "Eggplant Onesie",
    "Sunflower Statue", "Potato Statue", "Christmas Tree", "Gnome", 
    "Sunflower Tombstone", "Sunflower Rock", "Goblin Crown", "Fountain", 
    "Woody the Beaver", "Apprentice Beaver", "Foreman Beaver", "Nyon Statue", 
    "Homeless Tent", "Egg Basket", "Farmer Bath", "Mysterious Head", 
    "Tunnel Mole", "Rocky the Mole", "Nugget", "Rock Golem", "Speed Chicken", 
    "Rich Chicken", "Fat Chicken", "Ayam Cemani", "El Pollo Veloz", 
    "Farm Cat", "Farm Dog", "Chicken Coop", "Gold Egg", "Easter Bunny", 
    "Rooster", "Nancy", "Scarecrow", "Kuebiko", "Golden Cauliflower", 
    "Mysterious Parsnip", "Carrot Sword", "Sunflower Amulet", "Carrot Amulet", 
    "Beetroot Amulet", "Green Amulet", "Warrior Shirt", "Warrior Pants", 
    "Warrior Helmet", "Sunflower Shield", "Skull Hat", "War Skull", 
    "War Tombstone", "Undead Rooster", "Immortal Pear", "Treasure Map", 
    "Basic Scarecrow", "Bale", "Scary Mike", "Laurie the Chuckle Crow", 
    "Poppy", "Kernaldo", "Grain Grinder", "Sir Goldensnout", "Beta Bear", 
    "Peeled Potato", "Christmas Snow Globe", "Wood Nymph Wendy", 
    "Cyborg Bear", "Palm Tree", "Beach Ball", "Cabbage Boy", "Cabbage Girl", 
    "Heart Balloons", "Flamingo", "Blossom Tree", "Collectible Bear", 
    "Pablo The Bunny", "Easter Bush", "Giant Carrot", "Maneki Neko", 
    "Squirrel Monkey", "Black Bearry", "Hoot", "Lady Bug", "Freya Fox", 
    "Poppy", "Grain Grinder", "Kernaldo", "Queen Cornelia", "Purple Trail", 
    "Obie", "Mushroom House", "Maximus", "Iron Idol", "Heart of Davy Jones", 
    "Karkinos", "Emerald Turtle", "Tin Turtle"
]

#All food NFTs
food_to_display = [
    "Mashed Potato", "Pumpkin Soup", "Bumpkin Broth", "Boiled Eggs",
    "Kale Stew", "Mushroom Soup", "Reindeer Carrot", "Kale Omelette",
    "Cabbers n Mash", "Roast Veggies", "Bumpkin Salad", "Goblin's Treat",
    "Cauliflower Burger", "Pancakes", "Club Sandwich",
    "Mushroom Jacket Potatoes", "Sunflower Crunch", "Bumpkin Roast",
    "Goblin Brunch", "Fruit Salad", "Sunflower Cake", "Potato Cake",
    "Pumpkin Cake", "Carrot Cake", "Cabbage Cake", "Beetroot Cake",
    "Cauliflower Cake", "Parsnip Cake", "Radish Cake", "Wheat Cake",
    "Mushroom Pie", "Honey Cake", "Kale & Mushroom Pie", "Orange Cake",
    "Blueberry Jam", "Fermented Carrots", "Sauerkraut", "Fancy Fries",
    "Apple Juice", "Orange Juice", "Purple Smoothie", "Power Smoothie",
    "Bumpkin Detox",
    "Bumpkin ganoush", "Eggplant Cake", "Cornbread", "Popcorn", "Apple Pie"
]

